/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIdemo */

#ifndef _Included_JNIdemo
#define _Included_JNIdemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIdemo
 * Method:    testHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIdemo_testHello
  (JNIEnv *, jobject);

/*
 * Class:     JNIdemo
 * Method:    testPrint
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNIdemo_testPrint
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNIdemo
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JNIdemo_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     JNIdemo
 * Method:    nativeSetAge
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_JNIdemo_nativeSetAge
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     JNIdemo
 * Method:    nativeGetAge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNIdemo_nativeGetAge
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
