/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNItest */

#ifndef _Included_JNItest
#define _Included_JNItest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNItest
 * Method:    testHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNItest_testHello
  (JNIEnv *, jobject);

/*
 * Class:     JNItest
 * Method:    testPrint
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNItest_testPrint
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
